### ISSUE TITLE
Advancements are announced at start of the new game.

### ISSUE THREAD

**Issue by realjbtytm** [Minehut/TeamGG#23]
It is not really anything major, but it is annoying. It shows the players advancements in the chat at the start of each game. One solution is to keep advancements announcements off, or just disable advancements entirely. Thanks.

[Screenshots](https://imgur.com/a/Fe6hZ)

**Comment by tjhubz** [comment]
Fixed by @MatrixTunnel

**Comment by Draem** [comment]
@lukechatton request lock :3 #26
