### ISSUE TITLE
Breaking the map.

### ISSUE THREAD

**Issue by HazryG** [Minehut/TeamGG#7]
You should only be able to break placed blocks/cobweb/any blocks like that, not blocks that affect the game such as the actual clay on the hill.

**Comment by 2OW** [comment]
Hey hazry you meanie I discovered that first. D:

**Comment by HazryG** [comment]
You didn't put it on here though :^)

**Comment by lukechatton** [comment]
This is an issue with the map configuration. Maps should include a filter on the capture point that disables building.
